### ISSUE TITLE
Storageformat of staticData

### ISSUE THREAD

**Issue by joergfunger** [nutofem/nuto#11]
For several reasons we need to restructure the way we handle static data. 
- The first reason is that we want the constitutive laws to be independent from the elements, so that unit testing is easier to do. In addition, this would allow to include external routines (such as abaqus or Ansys usermats) easier.
- The second reason are the constitutive formulations that include multiple constitutive laws. In this case, it seems to me advantageous to directly have a "multiple constitutive static data object" that hierarchically allocates the corresponding static data (similar to the law itself). 

However, there are several problems. In line with the current changes of @Psirus , the question remains, if we should copy the static data, or forward references. Copying would also mean that the update would no longer be done on the constitutive level, but it would return a newStaticData object that is then copied/moved on the element/pde level.
The second question is related to the multiple static data objects introduced by @TTitscher to deal with IMPLEX, Euler backward/forward etc. If we store a vector of static data at the IP level, then we can only choose the static data to be used once at the element level. If this is not what we want (in the extrapolation this is not useful) we could have the Static data be build as templates, with the template parameter corresponding to the number of prev/next time derivatives.
A third question is now related to the question, why our input/output objects are not directly Eigen::Matrices. Looking at the first point (static data as input to the evaluate of the constitutive model), we realize that these static data objects are not really Eigen::matrices. This means, we could have another two input/output maps of "other objects". We could (and currently are doing it this way) use casts or AsEigenMatrix() functions (the latter option is what I prefer). Generalizing this approach would also mean to get rid of strains, stresses etc. and only use eigen::matrices instead.

**Comment by TTitscher** [comment]
No solution but another thing to think about:
- efficient (manual?) serialization for the restart files

**Comment by TTitscher** [comment]
This issue is solved in Branch StaticData2, ready to merge with master. You can read the documentation in doxygen: developer docu/ConstitutiveStaticData.
Basically:
- each law has a corresponding IP law that contains its static data.
  - IP law is a template class with the template argument 'law'
  - it automatically calls law.Evaluate() with the suitable data, no dynamic_cast<>(...)
- each integration point has a IP law
- Serialize via NuTo::SerializeStreamIn/NuTo::SerializeStreamOut 
  - see docu for that in developer docu/NuToSerializeStream

We are currently doing some code review and will merge asap.

**Comment by Psirus** [comment]
Finished with commit caa0b6e4c34a9a020498a2f866ac8bf4ceecc642
