### ISSUE TITLE
PDE access integration point data

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#129]
We need to access the data on each integration point for
- visualization files
- restart files
- other post processing
- tests (stress == expected stress?)
- ...

and there is currently no pattern for that.

### Possible data structure

- define `IpValue` as a single data entry at an integration point
~~~cpp
struct IpValue
{
    std::string name;
    Eigen::VectorXd data;
};
~~~
- one integration point may want to visualize several data entries. Collect them in 
~~~cpp
using IpValues = std::vector<IpValue>;

// e.g.
IpValues valuesAtASingleIntegrationPoint = {{"Stress", Eigen::Vector3d(...)}, {"Strain", Eigen::Vector3d(...)}};
~~~
- each cell has several integration points. Collect them in a vector
~~~cpp
virtual std::vector<IpValues> CellInterface::XYZ???(???) = 0;
~~~

### Possible interface

Some options where the integrand visualizes all its data:
- demand a `virtual IpValues Integrand::Interface::GetIpValues() = 0;` for all integrands
- add a `VisualizeAllOperation`

It may be nice to return only part of the integration point values
- add multiple visualize operations `VisualizeStrainOperation, VisualizeStressOperation`
- stick to one operation/method an provide options as arguments
    - `Integrand::GetIpValues({"Stress", ...});`
    - `Cell::Visualize(VisualizeOperation({"Strain", "Stress", "Damage"});`

Or something completely different.

Ideas?

**Comment by Psirus** [comment]
With the danger of angering someone over my repeated insistence on this, I think these things would be much easier if you just have a single integrand that stores all the history. Restart files simply become `outstream << myIntegrand`, and visualization should just call one method multiple times, say `integrand.GetOutput("Stress", cellId, ip)` instead of defining yet another data structure `IpValue`. The same goes for tests.  

In terms of visualization, I would probably favour an interface with strings, so e.g.

~~~cpp
visualizer.Visualize(["Stress", "Strain"])

// in Visualize(outputList):
for cell in cells:
    VisualizeCellGeometry(cell)
    VisualizeCellData(integrand, cell.Id, outputList)

// in VisualizeCellData(integrand, cellId, outputList):
for output in outputList:
    data = integrand.GetOutput(output, cellId)
    WriteCellData(output, data)

// equivalent for IPData if desired
~~~

**Comment by TTitscher** [comment]
I like the idea of requesting data (via this string) - and, as for the integrand discussion, I am sure this can be implemented in both approaches. `integrand.GetOutput("Stress", cellId, ip)` vs `cell.GetOutput("Stress")[ip]`, ... another issue on that? :ghost: Back to the track.

Now I see that there would be a redundant string for each integration point if we would have used the `struct IpValue`. I like your idea much better.

I am wondering, if we can come up with something better than strings. In contrast to enums, they are easily extendable but are prone to typos and lack auto completion. If we stick to strings (and I do not have a clear alternative in mind...), some followup questions: 
- What happens if the Pde does not support the requested output. Throw? Nothing?
- Do we define a certain naming convention? 
- Imagine:
~~~
std::vector<std::vector<Eigen::VectorXd>> vals = something.GetIpData({"Stress", "Strain", "Damage"});
      ^^^          ^^^
   each IP    each ip data
~~~
So "Stress" is the 0th entry, "Strain" the 1st, ... Is this enough? Or do we want to provide a class for that?
~~~
CellIpData vals = ...;
for (auto stressIp : vals["Strain"]) // extracts "Strain" for each ip
   ...
~~~

- Will all of this just develop over time when we run into problems?

---

(Restart files may not fall into the same category as the other cases I mentioned. They just write or read _all_ history data to/from some file. Without selection. So maybe they are not relevant for this discussion anymore.)

**Comment by Psirus** [comment]
I'm not sure this "integrand discussion" is quite as irrelevant as you make it out to be. For example
> What happens if the Pde does not support the requested output. Throw? Nothing?

and
> Do we define a certain naming convention?

are moot. Your integrand, your problem. Not ours.

What do I need this for

    std::vector<std::vector<Eigen::VectorXd>> vals = something.GetIpData({"Stress", "Strain", "Damage"});

**Comment by TTitscher** [comment]
We want to have an integrand library with some common pdes - regardless of the "integrand concept" used. At least in this lib, they should behave similar in some cases. Naming convention: If I visualize "Stress" in a linear elastic pde, can I expect the stress in a phase field pde to be named "Stress" as well? Throw or not: Can I expect NaNs in my result file or an exception if there is no "Stress"?
And this also concerns the visualizer, as a _core_ feature. How should the visualizer handle an empty data vector that may be returned if a custom integrand does not throw? Exception? NaN? 

> What do I need this for

Ehh.. you called it `integrand.GetOutput`... Returns one data entry per integration point of my cell, or `cellid`. Or do you mean, why multiple requests at once? Building the jacobian and the B matrix is the most expensive part. We can minimize that by querying all outputs at once. If this is too much of an optimization, we can ignore that for now.

**Comment by Psirus** [comment]
> Naming convention: If I visualize "Stress" in a linear elastic pde, can I expect the stress in a phase field pde to be named "Stress" as well?

Fair enough, but this concerns the PDE library, not the visualizer.

> How should the visualizer handle an empty data vector that may be returned if a custom integrand does not throw? Exception? NaN?

Okay, I've not considered that. Spontaneously, I'd say NaN, but I don't know.

> Or do you mean, why multiple requests at once?

Yes, that's what I meant. I'd ignore this for now, sure Jacobians are expensive, but compared to disk access? Seems like a wild interface for a solution to a problem that we're not even sure we have. :)

**Comment by TTitscher** [comment]
> Fair enough, but this concerns the PDE library, not the visualizer.

Yip. And this issue is not (only) about the visualizer here. whatever :)

Luckily, there is a LinearElasticityVisualize benchmark that you can profile. I just did. The visualization of displacements, stress, strain, principal stress for 10x10x100 quadratic bricks takes roughly 1.1s. The actual disk write takes 4% of the time. DetJ and B takes 8% in total and they are only called once per integration point. I am totally with you to ignore that for now. But keep it in mind...
(InterpolateDofGlobal takes 40% of the time, what the....)

**Comment by Psirus** [comment]
Although we both agree to ignore it, I still have a couple of remarks regarding this benchmark. Did you write to a SSD or HDD? More importantly, the kernel keeps data in a buffer cache in the memory to avoid slow disc access. So depending on the file size (and 15MB doesn't seem that much compared to, say 8GB of RAM) your file may have never seen the disc. I think you can use [sync()](https://linux.die.net/man/2/sync) if you want to force it to write. Let us know what you find. **Edit:** Hard discs have caches as well. For modern drives, those might be up to 64MB. Just FYI.

**Comment by TTitscher** [comment]
Ouf, seems complicated. So the benchmark may be pointless. Lets stick to the _ignore it_.

**Comment by vhirtham** [comment]
Okay, the current status can be found in the PDE_ip_data branch. There are several questions, that need to be addressed and I want to discuss them here now:

**1. Data structure**
Currently the history data is stored at the integrand / law as a map of vectors of our IP data. This is not optimal and a boost::multi_array or a plain std::vector would be better. However there are the following problems we need to think of:

- The Cell numbering has to be in the range [0, ... numCells]. How do we archieve this? joergfunger suggested an extra class that holds the cell group and the integrand which is passed to the build routines of the assembler. This class can do the numbering once (on construction) or just pass the number while looping over the cells. 

- The integration points need to be the same for each cell or we need a lookup table like the one used in sparseCSR matrices.


**2. Initialize history data**

Since we are using one big block of data to store all the history variables, we need to initialize this block at some point with the correct size and some initial values. 
The initial values can just be written as default values in the history data struct and for varying values I would add some kind of SetHistoryData(int cellNum, int ipNum) function. Or just take a getter which returns a non const ref.
However the resizing of the container has to be done at some point, where the size is known. Should the user do the initialization manually or do we wan't to do this automatically? If we wan't to do it automatically, where?
In case of using a data structure that joins integrand and cell group as suggested in **1.**, we can do it there.


**3. Update history data**

I had an discussion about updating history data with joergfunger. As far as I understood him, the "problem" in the "old" NuTo is that the history variables (for example strains of previous time step) need to be evaluated again before they are stored.
Instead of evaluating two times - one time for the iteration and one time to update history data - we can keep a copy of the results in an history data object. Updating would than be a simple memcpy (if we have an contiguous underlying data type). What do you think? 
@joergfunger : Feel free to edit this comment if you think my description of the problem is not sufficient  

**4. Hide history data in a separate class** 

A "standard user" might not want to mess around with internal history data management. Therefore we can generate a history data class, that does all the necessary setup itself. Maybe something like this:

```
template <typename T>
class HistoryData
{
    highEfficiencyContainer<T> mHistoryData
public:
    void InitializeHistoryData();

    T GetHistoryData(int cellNum, int ipNum) const;
    highEfficiencyContainer<T> GetHistoryData() const;

    UpdateHistoryData(highEfficiencyContainer<T> newData);
};
```

You just derive your Integrand from that class like this:

```
struct myHistoryData
{
    int myHistoryInt = 42;
    float myHistoryFloat = 1337.;
}

class myIntegrand : public HistoryData<myHistoryData>
{
    ...
}
```

Thats all for now. Looking forward to hear your opinion.

**Comment by joergfunger** [comment]
Just to rephrase the previous discussion a little bit. Currently, the update of the history data requires another loop over the cells and further the evaluation (return mapping,..) of the corresponding data. Instead, we could return somehow (not sure how) the history data state as an output. Then, an update would just be a copy on the integrand level (no loop over the cells). Furthermore, this update could also be done in a different way (IMPLEX, cycle jump) - just on the integrand level. Last but not least, keeping different sets of history data at the same time allows to do higher order schemes (with not only the previous time step as an input).

**Comment by TTitscher** [comment]
I still think that the user should decide. The `Core` of NuTo provides the basics, in this case some way of passing a cellId and ipId to the function that the cell integrates. So the cell could simply have an `Id` in its ctor. If the user correctly numbers his cells is IMO another question. Of course, we can and should help him. 
We could offer this cell/integrand combination 
~~~cpp
template <typename TIntegrand, typename TCell>
struct InsertSuitableName
{
  TIntegrand mIntegrand;
  std::vector<TCell> mCells;
  /* maybe */ Group<CellInterface> mCellGroup;
};
~~~
that takes care of the numbering. But this should be no requirement. The user is free to chose an arbitrary numbering.

Similar goes for the history data container. Again, we _could (and should)_ provide a helper class for that, e.g. a wrapper for `std::vector<T>` that additionally provides the `T& operator(int cellId, int ipId)`. But for a damage model with only one history variable, I personally want to chose a `Eigen::MatrixXd`. I can trivially perform cycle jump stuff like
~~~
integrand.mHistory += deltaHistory * numCycles;
~~~
And it would be a pain, if I am forced to use the `std::vector` based history data, because I would have to implement `+=` and `*` manually.

---

For me, the real question is, how do we design our integrand library so that the user can conveniently build his own integrands. But this is another issue. I really think that an arbitrary `int cellId` that is passed to the cell's ctor and further passed to the `CellData` object enables the user to handle history data and, thus, completely solves this issue. 
__Edit:__ I actually solves #44, but you somehow chose this issue for you comment :P

**Comment by vhirtham** [comment]
I think I agree with you on the numbering. Passing the IDs by the ctor is probably the most flexible way. Only question is, how we tell the "user" that it is his responsibility to create a _unique_ cell numbering? 

Also agree on the helper class as a "could".

With this cell-integrand merger class comes one question for me: Should this always be necessary or not?
If not, we have to provide two interfaces for the `BuildGradient` etc. routines. That doesn't make sense IMHO. So I think the best way is to use this class as a "must". 
We can offer different ctors for this class. One default ctor, that does the numbering of the cells in a standard way and a ctor that takes an individual numbering function. That would also solve the problem of the users responsibility for the cell numbering without loosing flexibility.

**Comment by TTitscher** [comment]
You can think of cell-integrand merger class as a pure convenience class that only provides an additional layer, again, only for convenience. Currently, there is this `SimpleAssembler` that takes a `Group<CellInterface>` as an argument. With the (IMO very reasonable) introduction of this cell-integrand merger class, this should not change.

~~~cpp
// you can still call
auto v = assembler.BuildVector(someCellGroup, ...)
// or use 
auto v = assembler.BuildVector(cellIntegrandMerger.CellGroup(), ...);
~~~

So there is no reason to change existing interfaces.

**Comment by vhirtham** [comment]
As far as I understood joergfunger, the plan was to pass the complete object to the assembler, but might have gotten that wrong. However, that is not so important now. I think I can finish the creep implementation in the test today. Then we have a working, history data based test and can start adjusting to the "optimal" solution.

**Comment by TTitscher** [comment]
Just one more remark. If you want to add a creep law, that should be
another PR. And you should ideally test it without a cell. And more
important, test the cell without the creep law. (You could call a cell
method with a test method that just checks the cellid.)

**Comment by vhirtham** [comment]
The creep law is just a side effect to test the IP data. So far it is not available outside of the test and its also just 1d. If everything works, we should probably move this "test" to the examples for a user implemented law with IP data and write a real unit test for the history data. I doubt that we need the full patch test to check if the IP data is working. 
I just started with the patch test to get used to PDE. I tried to implement a history dependent law which I can actually check for correctness by comparing the results to the theoretical solution. Creep was the simplest example for me, since it needs no additional dofs or stuff except for the history data. If I move this to our integrand library I will write a proper test for it.

**Comment by vhirtham** [comment]
Just pushed the working test. I will start a pull request tomorrow and highlight the important parts of the current implementation. I will also discuss several code snippets. Than we can start discussing the necessary changes in detail (Think there are several).

**Comment by TTitscher** [comment]
This is just an update of this issue to get back on the original topic on access of integration point data. The current idea is presented in #130. You define a function, much like a `Gradient` or `Hessian` function, that simply returns your desired result. This function is evaluated by `Cell::Eval(f)` that collects the results for each integration point in a vector. E.g.
~~~cpp
auto IpStress = [&](CellData cellData, CellIpData cellIpData)
{
   auto strain = cellIpData.GetB() * cellData.ExtractNodalValues();
   return customIntegrand.GetLaw().Stress(strain);
}
//...
std::vector<Eigen::MatrixXd> ipStrains = cell.Eval(IpStrain);
std::cout << "Strain of integration point 2: " << ipStrains[2] << '\n';
~~~
