### ISSUE TITLE
PDE nodal values

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#141]
# Problem

a) 
- no concept for time derivatives of nodal values
- having `NodeMerge`
    - nodal values are some internal state, _impure_ functions

b)
- elements contain node references
    - not trivially copyable elements

# Solution

a)
- introduce a `SolutionVector` object that stores the nodal values, including time derivatives, values of previous time steps or whatever - [ nice idea of @joergfunger ]
- only store dof numbers at the node
- (have dedicated coordinate nodes that have coords)
- nodes could look like

~~~cpp
struct CoordinateNode
{
    Eigen::VectorXd mCoords;
};

struct DofNode
{
    std::vector<int> mDofNumbers;
};
~~~

b)
- replace node _references_ with node _values_ at the elements
    - duplicate information, but:
    - trivially copyable
    - no _central_ node container (no need for operations on all nodes)

### Interface changes

Mainly pass the `SolutionVector` to the cell/assembler. 

~~~cpp
int main()
{
    // ...
    SolutionVector v(numDofs);
    auto gradient = assembler.BuildVector(gradientFunction, v);
}

Vector Cell::Integrate(Function f, SolutionVector v)
{
    for (auto ip : mIps)
    {
        // ...
        CellData cellData(element, v);
        f(cellData, cellIpData); // same interface
    }
}
~~~

### Possible implementation

~~~cpp
NodalValues CellData::GetNodalValues()
{
    return Memoized(mElement.ExtractNodalValues(mSolutionVector));
}

NodalValues ElementInterface::ExtractNodalValues(SolutionVector v)
{
    NodalValues nodalValues
    for (auto node : mNodes)
        for (int dof : node.Dofs())
           nodalValues.push_back(v[dof]);
    return nodalValues;
}
~~~

# Discussion

- Sounds good?
- Naming? `SolutionVector`? `SolutionVectors`? `DofValues`? `DofValueVectors`? `...`?
- Will this work with IGA straight forward as well?
- It will introduce some more dependencies: The element alone can no longer calculate stuff, it always needs a solution vector passed to it. This may make tests a bit more annoying.

**Comment by vhirtham** [comment]
Can you explain the problem a little bit more in detail for people who didn't join the discussion that took place before and who don't know every detail about the PDE  concept (yet)? Would be beneficial to get more people involved.

- Why is it a problem that nodes have an internal state and why is it beneficial to have another object / class that is needed?
- Why do I need elements to be copyable (in a trivial way)?

For the time derivatives:

- We can just define them as another dof type 
- We can expand the dof vector. If I have 3 dofs for a 2d displacement vector without time derivatives, I have 6 dofs for 1 time derivative and 9 for 2 etc.

**Comment by TTitscher** [comment]
Thanks for asking those questions!

> Why is it a problem that nodes have an internal state and why is it beneficial to have another object / class that is needed?

For someone that is not used to our current `NodeMerge` concept, it may be confusing why we do
~~~cpp
structure.NodeMerge(solution);
auto g = structure.BuildGradient();
~~~
instead of
~~~cpp
auto g = structure.BuildGradient(solution);
~~~
The latter one is far more obvious.

But now imagine you deal with time derivatives. How could the interface look like?
~~~cpp
auto g = s.BuildGradient(dt0, dt1, dt2); 
~~~
What, if you have a static problem without time derivatives? So the idea is to wrap those in a `SolutionVector` (name debatable). Then, the user defined gradient function can extract whatever time derivative it needs. 

> Why do I need elements to be copyable (in a trivial way)?

In some occasions, we want to _split_ our mesh. I think of mesh partitioning in MPI parallelism. Or there are techniques for dynamic load balancing that takes elements from one process and puts it into another one. It is just easier, if you can copy the elements. 
Currently, we allow `move`ing the mesh. This forces the user to use `auto newMesh = SomeMeshFunction(std::move(mesh),...)` which may be confusing. And the `mesh` object is invalid afterwards.

> We can just define them as another dof type

Yeah, we can, indeed another option. But then we need to keep the dof numbering of the time derivatives in accordance with the values. Then we may introduce constraints to some dof values. This requires renumbering of the dofs _and_ of the time derivative dofs. For me, this seems too error prone.
Another idea is to store the time derivatives at the nodes, as we do in _old_ NuTo. The main point here is again the removal of the _impurity_ of `NodeMerge`.

> We can expand the dof vector. If I have 3 dofs for a 2d displacement vector without time derivatives, I have 6 dofs for 1 time derivative and 9 for 2 etc.

I do not get the question. Will this aim for avoiding the additional `SolutionVector` object? The idea of @joergfunger involves defining _arbitrary_ numbers of solution vectors. They _may_ represent our current time derivatives `dt0, dt1, dt2`. But you could also define vectors for past time steps, like `dt0_n-3, dt0_n-2, dt0_n-1, dt0_n`.

**Comment by joergfunger** [comment]
We should also discuss, if the solution vector should be separated into a dependent and an independent part, or if this is a unique vector. 

Two vectors
- the global solution vector can directly be used 
- the domain solution of the dependent dofs can then be calculated afterwards
- the lookup on the cell level is more complicated. Why should a cell/integrand care, whether the dof solution of a node is a dependent/independent dof

One vector
- requires to assemble this vector as a function of the solution vector containing only the independent dofs

When dealing with the generalized time integration schemes and solvers, the global solution is certainly a standard vector (or similar, but not a block vector), thus we will have to copy the solution anyway. My suggestion would be to make the solution vector that is passed to the gradient/hessian cell functions independent of the constraints (thus I'm in favor of option single vector).

**Comment by vhirtham** [comment]
@TTitscher 

Well if you don't want the user to call `NodeMerge` you can just put it into the `BuildGradient` routine and then you have the same interface: 

~~~cpp
auto g = structure.BuildGradient(solution); // Calls NodeMerge(solution) internally
~~~

> I do not get the question

My bad, the second part of my answer was ment as alternative suggestions. If you actually take my second suggestion by just storing the time derivatives on the dof  ype (expand the dof vector by the derivatives) there won't be any need for a special interface like 'auto g = s.BuildGradient(dt0, dt1, dt2);'. I mean the integrand knows what he needs and just asks the current cell to provide the dof values:

~~~cpp
NuTo::NodeValues u = cellData.GetNodeValues(mDofType);
~~~

We just need to change the 'cellData.GetNodeValues' Interface to also take a number for the time derivative (default = 0). If I am not missing something, these two changes will achieve the same things without the need for this solution vector stuff, except for the 'purity'.  

> Will this aim for avoiding the additional SolutionVector object?

Yep, indeed. I am just not convinced so far, why we need it and I don't know if it and its side effects are easier to understand for a random user than a 'NodeMergeDofValue' routine. Don't get me wrong. I don't want to say it does not make sense. I just can't see it so far.

**Comment by TTitscher** [comment]
@vhirtham These two things together (no `NodeMerge` and no central `NodeVector`) that made me think this way. Your idea is following the approach in our master branch. And this is proven to work nicely. But as soon as I thought about the element copies, I found this way to be not great. Maybe @joergfunger can list further advantages as it is his idea in the first place.

@joergfunger Both the _one vector_ and _two vectors_ versions are advantageous in certain situations. So maybe we should decouple the `GlobalVector` (physically storing `J` and `K`) with the concept of `views`. So we always store the full vectors `[0..numDofs]` and have methods `J(), K()` that return _a view_ into the independent/dependent part of the global vector. Eigen does that with [`Eigen::Ref`](https://eigen.tuxfamily.org/dox-devel/classEigen_1_1Ref.html). In the simplest case, we could have our 
~~~cpp
using DofVector = DofCalcContainer<Eigen::VectorXd>
~~~
_and_ a
~~~cpp
using DofVectorView = DofCalcContainer<Eigen::Ref<Eigen::VectorXd>>

DofVectorView GlobalVector::J()
{
// ... 
  dofVectorView[dof] = mGlobalVector[dof].segment(0, NumIndependentDofs());
}

DofVectorView GlobalVector::K()
{
// ...
   dofVectorView[dof] = mGlobalVector[dof].segment(NumIndependentDofs(), NumDependentDofs());
}
~~~

**Comment by joergfunger** [comment]
@vhirtham  : The main advantage in my opinion is the decoupling of the interfaces. It is way more logic to call f(disp) than setting an internal variable disp and then calling f(). Furthermore, we are able to hand in multiple solution vectors (e.g. disp, vel acc, or the solution at t-2 and t-1). This can be user-defined. Adding the time derivatives as an additional dof is somehow tricky. If you were to add it as another global dof (which is possible), you would have to define the evolution equation that relates velocities and displacements at the global level (which is also possible). But this would mean to blow up you global system of equations by a factor of 2 (d and v instead of only d). If we find a way to define this as a subproblem (condense out v as a function of d, and then reduce your system to only d), this would be possible.

@TTitscher The idea of the views is nice. However, I'm still confused with the blockvector approach. The full solution that we are passing to the cells is certainly of the block structure, the global solution vector is almost certainly a single vector in the solver format (so in this case e.g. trilinos), so maybe there has to be a conversion between these types anyway. But maybe there is also the option of directly writing the solution vector from trilinos into the mGlobalVector.

**Comment by TTitscher** [comment]
I currently favor a solution object that contains many global dof vectors, simply like
~~~cpp
using SolutionVector = std::vector<GlobalDofVector> globalDofVectors;
~~~
You have to provide them in the assembler methods. They are transferred to the `Cell::Integrate(f, solutionVector)` methods and passed to `CellData`. From there, you should still be able to call `CellData::ExtractNodeValues(id)`. So the integrands will not change. 
The meaning of this `vector` or the `id` above is arbitrary and user defined. One reasonable choice may be
~~~cpp
auto displacements = SolutionVector[0];
auto velocities = SolutionVector[1];
auto accelerations = SolutionVector[2];
// and inside e.g. Integrand::Gradient: 
auto velocity = cellIpData.ShapeFunctions() * cellData.ExtractNodeValues(1);
~~~
Or you do something with multiple time steps like
~~~cpp
auto displacements = SolutionVector[0];
auto previousDispl = SolutionVector[1];
~~~
Point is, we do not have to decide that and choose one. In one main file, the user may use the first version. In another example, he may choose the second or a completely different meaning of these entires. (As always, in an `IntegrandLib` we have to find a common handling of those. But this is an other discussion.)

Apart from that, there are some things to consider:
- You are no longer able to call `node42.GetValues()`. You always have to provide the `SolutionVector` and we may end up with `auto disp = NuTo::NodalValues(node42, solutionVector);`. Same goes for setting nodal values, e.g. for tests. `NuTo::NodalValues(node42, solutionVector, newDispls);`
- You are required to pass the solution vector. For a linear problem, it may seem strange to pass a `SolutionVector` full of zeros to the assembler. (Or we provide this zero vector as a default argument...)
- Right now, things like calculating the gradient of a cell does not require dof numbers at the nodes. With this change, it does. This may make some unit tests longer and more complicated.
- We have at least two node types. `CoordinateNodes` only contain coordinate values. `DofNodes` only contain global dof numbers.

These are not severe arguments against this issue and I still like the general idea. But, as in many cases, it will make some things easier and more beautiful, other functions suffer.

**Comment by joergfunger** [comment]
We will have to decide how to deal with different dof types that each require a different order related to the time integration scheme. Take as an example a transient thermal problem that requires T and T', and coupled to this a mechanics problem with d, d' and d''. Standard time integrations schemes reduce the order by defining additional variables with additional equations (such as Q=T', v=d', a=v'). In the approach, where different solutions vectors are interpreted as different time derivatives, this would always require the same dimension of the time derivatives for all dof types (e.g. in the above case 0,1,2), even though T'' does not exist. I kind of like the idea of adding another dof type and another equation d'=v, where d' is discretized using any time integration scheme. In the case above, this would mean an increase of the dofs for the mechanics part by a factor of 3 and for the thermal part by a factor of 2. But it has several advantages
- The time discretization can be of different order for each dof type
- No need for additional interfaces (The time integrations schemes just get the dof types that should be related, e.g. d'=v)

But there are also some disadvantages
- The system of equations to be solved is larger. However, for explicit methods, this is not a problem, since this calculation and storage of the velocities/accelerations has to be done anyway, so there is no performance loss, and in the case of implicit methods, I would assume the solver (such as MUMPS) to realize the diagonal structure and thus the performance of the solution scheme should also not be significantly larger - there is only a single entry per row in the hessian_mod, since v=d' is usually done per node.
- The dof numbering should be consistent so that the velocities dofs of one node actually belong to the correct displacement dofs

**Comment by TTitscher** [comment]
@vhirtham and I had some discussions on that and we want to hear your opinion on the following __plan__:

## 0) Possibly apply #164

## 1) Introduce the `GlobalDofValues`

like
~~~cpp
class GlobalDofValues
{
public:
    double& operator(DofType dof, int globalDofNumber, int index = 0)
    {
        return mValues[index][dof][globalDofNumber];
    }
private:
    std::vector<DofVector> mValues;
};
~~~
Note that `index` is optional. I could stand for
    - `numTimeDerivatives`
    - `solutionStep`, `intermediateResult` like `n, n-1, n-2, n-3, ...`
and does not prevent you from defining time derivatives as additional `DofType`.

Adapt interfaces such as
~~~cpp
SimpleAssember::BuildVector(f, dofstypes, /*new:*/ globalDofValues);
CellInterface::Integrate(f, /*new:*/ globalDofValues);
ElementInterface::ExtractNodeValues(/*new:*/ globalDofValues);
CellData::CellData(...., /*new:*/ globalDofValues); // (ctor)
~~~
The `CellData` handles those values, so the `Integrands` remain untouched.

## 2) Split NodeSimple

... into
~~~cpp
struct CoordNode
{
   std::vector<double> mCoords;
};
struct DofNode
{
    std::vector<int> mDofNumbers;
};
~~~

Requires changes in `ElementInterface` e.g. `CoordElementInterface` and `DofElementInterface`.

## 3) Convenience functions

Maybe add a `AdvancedNode` that internally saves its dof type, coordinates, values, ...

## 4) Make elements copyable

Rough plan: As nodes are now _small_, we can save them by value at the elements. We could do the same for the interpolation types, e.g. as `shared_ptr`.

## What do you think?

**Comment by Psirus** [comment]
To me, this again seems like something the integrand cares about, but not really the assembler/cell/etc. This is why there are so many different things it could be (DOF values, time derivaties, previous solutions, etc.). And continuing this general trend of "the user/integrand" needs to know, I'd like to make it their responsibilty instead of creating this catch-all `GlobalDofValues` class.

Maybe something like this:

~~~cpp
// copied from PatchTest
MeshFem mesh = QuadPatchTestMesh();
DofType displ("displacements", 2);
const InterpolationSimple& interpolation = mesh.CreateInterpolation(InterpolationQuadLinear());
AddDofInterpolation(&mesh, displ, interpolation);

// new stuff starts here
DofValues u = mesh.CreateVector(mesh, displ);

LinearElasticity elasticity(C = 2e5);

auto H = [&](const CellData& cd, const CellIpData& cipd)
{
    return elasticity.Hessian0(cd, cipd);
};

auto f_int = [&](const CellData& cd, const CellIpData& cipd)
{
    return elasticity.Gradient(cd, cipd, u);
};
~~~

With a corresponding integrand that would look like this:

~~~cpp
// doesn't need any DOF values
LinearElasticity::Hessian0(const CellData& cellData, const CellIpData& cellIpData)
{
    BMatrixStrain B = cellIpData.GetBMatrixStrain(mDofType);
    return B.transpose() * C * B;
}

// needs DOF values
LinearElasticity::Gradient(const CellData& cellData, const CellIpData& cellIpData, DofValues u)
{
    BMatrixStrain B = cellIpData.GetBMatrixStrain(mDofType);
    DofNumbers dofnums = cellData.GetGlobalDofNumber(displ);
    NuTo::EngineeringStrain<TDim> strain = B * u[dofnums];
    return B.transpose * (C * strain);
}
~~~

**Comment by TTitscher** [comment]
I agree with your point that some integrands do not need nodal values. And following our previous principles, this should be addressed. And, as always, for an integrand lib, we could demand that for all integrands to have a unified interface. But I agree that it should be possible to evaluate functions that do not require nodal values. 

In your examples, `u[dofnums]` is evaluated for each integration point, where previously, it was evaluated once (in `CellData`). This seems like unnecessary work. And I still think that the node values somehow belong to the `CellData`. And, apparently, not every integrand needs `CellData`. But I have no clue how to solve that. :cry: 

__Edit:__ And we could on with this. Why is there `GetBMatrixStrain()` in `CellIpData`? Very specific for a FEM mechanics problem in voight notation. Maybe we should think about those objects...

**Comment by joergfunger** [comment]
Even though I think that the linear elastic case with integrands that do not require nodal values is a very special case, I kind of like the idea of having functions that do not require the solution vector. However, I also think that at least for the standard mechanics problems we will have to have a standard class the defines gradient, hessian with standard momentum balance. In this case the user will only have to e.g. change his constitutive model- in this case we should always pass the dof_values. Regarding the extraction of the  dof values for all integrands, there could be some intermediate function that extracts the dof values, instead of 
~~~cpp
NuTo::EngineeringStrain<TDim> strain = B * u[dofnums];
~~~
something like
~~~cpp
NuTo::EngineeringStrain<TDim> strain = B * cellData.GetDofValues(u,dofnums);
~~~
The last one is essentially what we are currently doing.

Regarding the discussion of @TTitscher 

0) The removal of the jk components in the global solution vector and instead use block views to access the different components is fine with me. The solution vector that is passed to the cells should **not** be renumbered. That means all nodes are created once and get unique and continuous dof numbers (entries in the global/domain solution vector). 
1) I also like this idea, but I'm not sure if a node has to now what dof type it belongs to. The nodes should always be accessed via the interpolation and the interpolation knows its dof type.
2) Splitting is fine with me, even though I think it could also be possible to just add the coordinates to this solution vector  similar to another variable (say temperature) that is not solved for in the current step, but the integrand is a function of this as well. That would simplify the interfaces since we have only a single interpolation type.
3) In what situations do we need advances nodes that internally save their dof type, coordinates, values, ?
4) If you store the nodes by value than numbering one node that is shared my multiple cells is not automatically renumbered in the other cell. In my opinion, this is the only advantage of still having a node, otherwise we could always directly access the corresponding entries in the solution vector and just store at the interpolation the integer values.

**Comment by TTitscher** [comment]
This issue somehow enables the development of integrands/schemes with multiple time derivatives. So even if we cannot agree on an _ideal_ design, I still think it is worth implementing it now. Since the `class GlobalDofValues` did not really cause _leaps of joy_, I suggest passing this data simply as
~~~cpp
Assembler::BuildVector(Group<CellInterface> cells, VectorFunction f, const std::vector<GlobalDofVector>& dofValues);
Cell::Integrate(VectorFunction f, const std::vector<GlobalDofVector>& dofValues);
~~~
It is also passed to `CellData`, so the integrands access nodal values like
~~~cpp
auto displacements = cellData.GetNodeValues(mDofType); // as before
auto velocities = cellData.GetNodeValues(mDofType, 1);
~~~
I am happy to hear further improvements or objections. 

__Edit:__ As for the idea of @Psirus. You propose to pass nodal values via stateful functions, like we do, e.g. for the time step, discussed here #145. So we define a lambda that takes nodal values and an integrand and returns a `Cell::VectorFunction`. And if I am honest, I somehow agree with this [comment](https://github.com/nutofem/nuto/issues/145#issuecomment-350249089). I don't know. So we _could_ write velocity dependent integrands using this technique just now. But maybe we think some more, before I implement stuff.

**Comment by joergfunger** [comment]
I think that this approach is reasonable, since I don't see many applications that do not require them.

**Comment by TTitscher** [comment]
___Please feel free to edit the Pro/Con lists below___

Some of the discussion is taking place outside github, especially about the numbering. So let us clarify the terms:
- *nodal values numbering* is the numbering that corresponds to a node and its position.
- *dof numbering* is the numbering in a system of equation, e.g. passed and returned from a solver

In PDE and old nuto, we do not have a *nodal value numbering*. The values are stored directly at the nodes. And the *dof numbering* depends on the linear constraints. In the approach with our `NodalValueVector`, we have to introduce a _nodal value numbering_. Some cases:

## _nodal value numbering_ == _dof numbering_

Pro: 
- implementation straight forward
- direct assignment of the solver result, maybe like
~~~cpp
nodalValues.J[displ] -= solver.solve(hessian, residual);
nodalValues.K[displ] = CalculateDependentDofs(nodalValues.J[displ], constraints);
~~~

Con:
- *nodal value numbering* now also depends on the constraints. So an exising `NodalValueVector` becomes invalid after changing constraints. Thus, the user indirectly has to care about the numbering.

## _nodal value numbering_ == const != _dof numbering_

We introduce a separate unique *nodal value numbering* (e.g. upon node creation) that does not change. The assembler takes care about the *dof numbering*.

Pro:
- `NodalValueVector` remains valid after changes of the constraints
- `NodalValueVector` does not contain J/K (details on how we deal with linear constraints)

Con:
- requires a mapping from one numbering to the other after each solve, like
~~~cpp
auto deltaIndepentendDispl = solver.solve(hessian, residual);
auto deltaDependentDispl = CalculateDependentDofs(nodalValues.J[displ], constraints);
nodalValues[displ] = DofToNodalMapping(deltaIndependentDispl, deltaDependentDispl);
~~~

**Comment by joergfunger** [comment]
I personally prefer the second variant - nodal value numbering = const != dof numbering. 
- a user that is not interested in the way how we handle our constraints, will always get a full solution vector that is constant over time, thus selecting a specific entry of the solution vector always corresponds to the same result (say the displacement at same point to be monitored).
- we could use the same solution vector  for different substeps when constraints are changed (say first moisture problem/drying without mechanical constraints, then a compression test with displacement control). In the case of nodal-value numbering = dof-numbering the transfer of the solution vector from the moisture step to the mechanics steps is imo not trivial.
- more complicated issues such as how we handle this numbering for multi-domain MPI-solvers (trilinos) is now only handled in this specific mappingClass - instead of mapping to a global solution vector for a single process, we could distinguish between domain and global numbers. Thus, the extension to  trilinos is less intrusive.
