### ISSUE TITLE
Design of element classes

### ISSUE THREAD

**Issue by phuschke** [nutofem/nuto#3]
### Design of element classes

The degrees of freedom should not correspond to a specific discretized PDE. 

Example:
`void NuTo::ContinuumElement<TDim>::CalculateElementOutputInternalGradient(...) const;`

Instead of looping over the active DOFs

```
for (auto dofRow : mInterpolationType->GetActiveDofs())
{
        switch (dofRow)
        {
        case Node::DISPLACEMENTS:
        // ...
        case Node::NONLOCALEQSTRAIN:
        // ...
        }
}
```

we should loop over the PDEs that we want to solve for specific DOFs

```
for (auto iPDE : GetPDE())
{
        switch (iPDE)
        {
        case PDE::BALANCE_OF_LINEAR_MOMENTUM:
        // ...
        case PDE::MODIFIED_HELMHOLTZ:
        // ...
        }
}
```

This avoids redundant code, increases flexibility, and enhances future implementation of strongly coupled PDEs.

**Comment by joergfunger** [comment]
The question is, how to design the PDE class, so that the correct operations are triggered in the element methods. Any ideas here are more than welcome. We could combine thermal/moisture problems as well as phasefield/gradient enhanced damage into a single module. In addition, this would allow to easily :) include other stuff such as e.g. pgd.

**Comment by TTitscher** [comment]
Maybe I am missing the point, but if I try to implement that in my mind I come up with the following problems:

The BALANCE_OF_LINEAR_MOMENTUM is for stresses. They often depend on strain (DISPLACEMENTS), so 
- dStress/dStrain
  has to be calculated.
  If you add an additional equation, e.g. the MODIFIELD_HELMHOLTZ for the gradient damage, you somehow have to calculate
- dStress/dNonlocalEqStrain. 
  If you use the MODIFIELD_HELMHOLTZ for PhaseField, you have to calculate
- dStress/dPhaseFieldVariable 

Where to put these "coupling" terms? To BALANCE_... or MODIFIED_...? How to define which dof to use?

**Comment by joergfunger** [comment]
This is right, but you could specify what your degrees of freedom in this equation are. I also would not call the equation balance of linear momentum, since this implies again stresses, but something like
div f = 0 (plus external forces, inertia terms etc.). Here, f is kind of like a free variable.
Furthermore, we should actually directly use the weak form
\int f : \grad u dV = 0. We then specify in the pde class how to calculate f (e.g. f=sigma(d,epsilon_nonlocal). Essentially, the pde class would be responsible for the calculation of the residual functions and derivatives. The element only provides the framework to calculate shape functions, derivatives etc (grad V, epsilon_engineering=sym(dV/dX,...) and the summation of the local residuals of each integration point.

Similarly for the heat equation A dV/dt - div (B grad V) = 0. In the latter case, V could be a temperature, or a moisture distribution, and then A and B are material parameters, but the general form is somehow identical. Also, A and B can be functions of other variables as well.

**Comment by TTitscher** [comment]
Ok, how could this PDE class look like?
@joergfunger s suggestion was that the PDE does the calculation and the element only provides N, B, and interpolated values.
The PDE class forwards the interpolated values as constitutive inputs to the constitutive law and requests outputs. Then, it combines the element outputs and the constitutive outputs to residuals/hessians in accordance to its specific PDE. 

But how to deal with coupled problems? Will there be a PDE_DivX.h and a PDE_mod_Helmholtz.h and you derive from both?

Additionally, there could be a PDE_Dynamic that somehow allows to add discretized equations via a user interface, e.g.

```
PDE.AddResidualTerm(DISP, B, STRESS);
PDE.AddHessian0Term(DISP, DISP, B, D_STRESS_D_STRAIN, B);
PDE.AddHessian0Term(DISP, EEQ, B, D_STRESS_D_NONLOCAL_EQ_STRAIN, N);
```

**Comment by Psirus** [comment]
Over the last week, I've played around with the idea of the PDE some more. In my mind, the PDE provides a sort of decoupling between the physics on one hand (stresses, strains, heat fluxes, etc.) and the discretization on the other (shape functions, nodal values).

My idea was that you could say

    myPDE.GetHessian0(element)

and the PDE would simply call things like `GetDerivativeShapeFunctions` and `ExtractNodalValues` of the element to calculate the output.

The laws would also belong to the element, so that physical meaning isn't lost in generic interfaces. E.g. the momentum balance should have a `StressBasedLaw`, so that it can call `GetStress`.

To maintain a strict seperation (it's up for debate whether this is necessary), I've also added something called `MechanicsState` (in case of the momentum balance), which is basically a pair of PDE and Element, so that a constitutive law can say `MechanicsState.GetStrain()` without having access to everything else in the Element or PDE classes.

A first prototype and a unit test (that gcc doesn't like for some reason) can be found on the [PDE branch](https://github.com/nutofem/nuto/tree/PDE).

This does not yet deal with

- static data
- coupled problems
- visualization
- many more things I probably didn't think about

It's not even integrated into the `ContinuumElement`, so no *real world* example either.

**Comment by joergfunger** [comment]
This is just a preliminary discussion on how to implement the PDE.  The main new feature would be a new class integration cell, which handles all the ip information. The elements are directly attached to this class. However, there is one element for each dof type (similar to the existing interpolation types that handle multiple dofs). Furthermore, dofs are no longer defined via enums, but instead, there is a separate dof-class. The constitutive input is defined via operators that are able to extract the constitutive input from the local nodal dof values and some further information from the interpolation type (shape functions, derivatives, ..). An exemplary code (not compiling) for the evaluation of element matrices/vectors is attached. In a multiphysics framework, a separate integration cell for each pde is required (which would allow for different integration schemes for different pdes). Each pde has a unique constitutive formulation. There would even be the option of having a separate pde/integration cell for different time derivatives, e.g. differentiating between the residual contributions from the stiffness and the mass matrix. Furthermore, external loads would also be directly handled as another PDE to simplify the interface (it is just another contribution to the residual that only depends on time). In this case, handling loads that are actually depend on the current deformation state would also be possible (e.g. when the normal direction of.a pressure is supposed to be in the deformed configuration).

![klassendiagramm](https://cloud.githubusercontent.com/assets/20501029/22434663/3c2f2000-e71d-11e6-817f-6da8c7999c8b.png)

```c++
Eigen::Matrix IntegrationCell::Evaluate(integrationCellOutput)
{
    
  // Determine localNodalValues (DofType is a separate class stored at the structure, not an enum)
  std::map<DofType, Eigen::Matrix> localNodalDofValues;
  for (auto inputDofType : mPDE.GetVectorInputDofTypes())
  {
    localNodalDofValues[inputDofType] = mVectorElements[inputDofType].GetNodalValues();
  }
    
  //loop over IPs and contributions
  std::vector<Eigen::Matrix> constitutiveInput(mPDE.mVectorConstitutiveInputs.size());
  for (auto ip : mIntegrationType.mIp.size())
  {
    //Evaluate all constitutive inputs from localNodalDofs and shape functions/derivatives
    for (auto itConstitutiveInputOperator : mPDE.mVectorConstitutiveInputOperators)
    {
      dofType = itConstitutiveInputOperator.mDofType;
      interpolationType = mVectorElements[dofType].mInterpolationType;

      //determine shape functions, derivatives, etc. .. 
      //required to calculate constitutiveInputs from localNodalDofValues 
      //(use here fixed values stored at the interpolation type)
      itConstitutiveInputOperator.CalculateShapeFunctionDerivatives(interpolationType,mIntegrationType,ip);

      //alternative determine shape functions, derivatives, etc. .. 
      //required to calculate constitutiveInputs from localNodalDofValues 
      //(use here natural coordinates at the interpolation type)
      itConstitutiveInputOperator.CalculateShapeFunctionDerivatives(interpolationType, ip.GetNaturalCoordinates());

      //now the required shape functions, derviatives etc. are all stored at the InputOperator
      //calculate the constitutive input such as strain, temperature, temperaturgradient, ...
      constitutiveInput[constitutiveInputCounter] = itConstitutiveInputOperator.Evaluate(localNodalDofValues);
    }

    //call the constitutive law with the input vector (all eigen::matrices, no enum required any more)
    mPDE.mConstitutiveLaw->Evaluate(constitutiveInput,constitutiveOutput,mHistoryData[ip]);

    //determine shape functions, etc. for the output operator 
    //(this is not fully optimal, since this would mean to recalculate e.g. B for the output operator as well)
    //maybe there could be something like a joint input/output operator
    mPDE.mOutputOperator->CalculateShapeFunctionDerivatives(interpolationType,mIntegrationType,ip);

    //determine shape functions, etc. for the output operator 
    residual += ip.Weight*Jacobian*mPDE.mOutputOperator->Evaluate(constitutiveOutput,integrationCellOutput);
  } 
}
```

**Comment by joergfunger** [comment]
Another issue that we should think of his the transfer of information between different objects. A good example is the operator class. It should return a constitutive input (strain, gradient, interpolated value, nonlocal strain,..) as a function of element informationen (shape functions/derivatives nodal values). Since it is not defined a priori, what this information is (shape function or derivatives), it is difficult to handle this in a general base class design. There are two options
- pass the element/interpolation type to the operator, or even pass the element to the constitutive formulation (or kind of like a wrapper) and call the required functions there (interpolate, gradient, nonlocal interpolate etc.)
-provide (similar as currently done with all input/output maps) a map of inputs that is allocated by the operator (what do I need), then passed via the integration cell to the element, it is there filled/calculated and then passed back to the operator

The first option is very flexible, but now the structure gets complicated (the input/output is not straightforward to see when looking at the code) and nested. Furthermore, the element (or a wrapper) is required in all constitutive formulations (which seems to me not an optimal design).

I prefer the second option, since it clearly separates the data flow, and it is directly obvious, what the input/output is - even though we need this input/output map now.

**Comment by joergfunger** [comment]
When separating the interpolation, integration and the pde, one idea was to directly define input strain2d and output stress2d
e.g.
class LinearElasticLaw2D
{
public:
    LinearElasticLaw2D(double rE, double rNu);
    Eigen::Vector3d Stress(Eigen::Vector3d rStrain) ;

private:
    double mE;
    double mNu;
    Eigen::Matrix3d mC;
}
 If we now implement the equivalent 3D-formulation, everything is identical, the only difference is the input/output dimension. This is somehow trivial in the elastic case, but for other formulations (e.g. plasticity the overhead, e.g. return mapping) is rather significant. How do we handle plain strain and plain stress, are these then two separate constitutive laws?

An alternative is keeping the interface general (Eigen::VectorXd) or even use the general maps currently used (input/output maps).

**Comment by TTitscher** [comment]
The input/output dimension can be solved with a dimension template. Maybe one could add the plane state as a template with separate specializations as well, like:
~~~cpp
struct PlaneStress{}; // just to be used as ...
struct PlaneStrain{}; // ... a template argument

template <int TDim, typename TPlaneState = void> // void means "I do not need a plane state".
class LinearElastic
{
public:
   Stress<TDim> Stress(Strain<TDim> strain);
   ...
private:
   Tangent<Voigt<TDim>> mC;
   ...
}; // class LinearElastic

template <TDim, TPlaneState>
Stress <TDim> Stress<TDim, TPlaneState>(Strain<TDim> strain)
{ /* default case */ return mC * strain;}

// specializations:
template <>
Stress <2> Stress<2, PlaneStrain>(Strain<2> strain)
{ /* plane strain here */}

template <>
Stress <2> Stress<2, PlaneStress>(Strain<2> strain)
{ /* plane stress here */}
~~~

**Comment by Psirus** [comment]
Solved in PDE.
