### ISSUE TITLE
History data in the PDE concept

### ISSUE THREAD

**Issue by joergfunger** [nutofem/nuto#44]
In the PDE-concept, the history data is directly attached to the integrand. So instead of the usual constitutive formulation (single object) and the static/history data (one for each integration point) and the code within the former element loop over integration points, the concept of the new integrand combines both, i.e. it is something like the (old) static data that knows how to calculate some functions at the integration point level. For this purpose, these Evaluate routines get the possibility via helper classes given as arguments to calculate shape functions / derivatives for all dofs, Jacobians...

A base class could look like this
~~~cpp
template <int TDim>
class IntegrandBase
{
public:
    virtual IntegrandBase<TDim>* Clone() const=0;
    virtual ~IntegrandBase()                             = default;
    virtual DofVector<double> Evaluate(const OptionBase& rOptions, const CellData&, const CellIPData<TDim>&)    = 0;
    virtual DofMatrix<double> Evaluate(const OptionBase& rOptions, const CellData&, const CellIPData<TDim>&)    = 0;
};
~~~

An integrand for our mechanics problems could look like this
~~~cpp
template <int TDim>
class IntegrandMechanics
{
public:
    virtual IntegrandMechanics<TDim>* Clone() const=0;
    virtual ~IntegrandMechanics()                             = default;
    virtual DofVector<double> Evaluate(const OptionBase& rOptions, const CellData& , const CellIPData<TDim>&)    = 0;
    virtual DofMatrix<double> Evaluate(const OptionBase& rOptions, const CellData&, const CellIPData<TDim>&)    = 0;
privat:
    const MechanicsLaw<TDim>& mLaw;
};

DofVector<double> IntegrandMechanics:::Evaluate(const OptionBase& rOptions, const CellData&, const CellIPData<TDim>&) 
{
switch rOptions.GetResultType():
  Residual: 
            NuTo::BMatrixStrain B = rCellIPData.GetBMatrixStrain(mDofType);
            NuTo::NodeValues u    = rCellData.GetNodeValues(mDofType);
            NuTo::DofVector<double> residual;

            NuTo::Strain<TDim> strain = B * u;
            residual[mDofType]     = B.transpose() * mLaw.Stress(strain);
            return residual;
}
~~~
NuTo::BMatrixStrain, NuTo::NodeValues are used typedefs for Eigen matrices (dynamic but statically allocated with fixed maximum size).

In this simple case, no history data is required - the mechanics law just calculates stress from strain.

### Option 1 proposed by @TTitscher 
The integrand could provide a basic interface to its history data. Each time integration uses this interface to manipulate the data from the outside - similar to the handling of nodal values.

~~~cpp
/* IntegrandBase */
virtual OwningPtr<HistoryDataBase> CalculateHistoryDataImplicitly() const = 0;
virtual void SetHistoryData(OwningPtr<HistoryDataBase> data) = 0;
~~~

The time integration scheme has access to all this data via
~~~cpp
OwningVector<HistoryDataBase> Structure::CalculateHistoryDataImplicitly() const;
void Structure::MergeHistoryData(OwningVector<HistoryDataBase> data) const;
void ExtractAndMergeHistoryData
~~~

... and can do stuff like ...

~~~cpp
/* Newmark at the start of a new time step */
historyData = structure.CalculateHistoryDataImplicitly();
structure.MergeHistoryData(historyData);
... = structure.BuildGradient();
...
~~~

or the more interesting case

~~~cpp
/* IMPL-EX or CycleJump */ 
// extrapolate
historyData_n_plus_1 = historyData_n + 1/timeStep * (historyData_n - historyData_n_minus_1);
structure.MergeHistoryData(historyData_n_plus_1);
...
// shift after sucessful iteration
historyData_n = historyData_n_minus_1;
~~~
(This requires overloading `operator+/-/*` for each static data type.)
Very specific methods like `AllocateAdditionalStaticData` and `ShiftToPast` are handled in the specific time integration scheme that uses them.

### Option 2 proposed by @joergfunger
The history data is only stored at the integrand - not on a global level. Each additional operation (extrapolate for cycle jump, implex, Euler forward of history data,...) is given via the OptionClass (see #43) in the Evaluate methods and has to be implemented in each integrand separately.  

~~~cpp
DofVector<double> IntegrandMechanics::Evaluate(const OptionBase& rOptions, const CellData&, const CellIPData<TDim>&) 
{
switch rOptions.GetResultType():
  Residual: 
            NuTo::BMatrixStrain B = rCellIPData.GetBMatrixStrain(mDofType);
            NuTo::NodeValues u    = rCellData.GetNodeValues(mDofType);
            NuTo::DofVector<double> residual;

            NuTo::Strain<TDim> strain = B * u;
                        
            residual[mDofType]     = B.transpose() * mLaw.Stress(strain,dynamic_cast<OptionsTimeIntegration>(rOptions)mUpdateHistoryVariables());
            return gradient;
}
~~~

Note that mLaw is not a constitutive law only, but also includes the history data

~~~cpp
template <int TDim>
class MechanicsLaw
{
public:
    virtual Stress<TDim> Stress(Strain<TDim>& rStrain) = 0;
    virtual Tangent<TDim> Tangent(Strain<TDim>& rStrain) = 0;
    virtual void UpdateHistoryData(Strain<TDim>& rStrain) = 0;
}

~~~cpp
template <int TDim>
class MisesPlasticity
{
public:
    Stress<TDim> Stress(Strain<TDim>& rStrain, const bool rUpdateHistoryVariables)
    {
         //perform return mapping and return stress
    }
    Tangent<TDim> Tangent(Strain<TDim>& rStrain)
    {
         //perform return mapping and return tangent
    }
private:
    Strain<TDim> mPlasticStrain;
    double mE , mNu, mRho;
}
~~~

**Comment by TTitscher** [comment]
Just an idea: each integrand allocates its data in a global history data vector and only holds a reference to it.
- no need to cast the history data in the integrand
- super fast extraction/merge (copy of somehow continuous memory)

**Comment by Psirus** [comment]
The description of option 2 already contains the deal-braker for me: "Each additional operation […] is given via the OptionClass […] and has to be implemented in each integrand separately.". If we have, say, a working Euler Forward implementation, I should not have to implement this again.

As I see it there are two levels that want to work on the history data: the time integration scheme (extrapolate, implex magic, ...) and the constitutive law (get new plastic stress, strain, etc.). I don't have a strong opinion (yet) on where we should store the data (in a global vector, at the integrand, at the cell), but we should find an interface that can handle both local (constitutive) and global (time integration) operations on them.

**Comment by TTitscher** [comment]
Somehow, some casual talk with @Psirus turned into a discussion on PDE concept and history data. Here are some findings.
We have the  PDE idea of @Psirus. The integrand is no longer stored at the cell but somehow outside. And data from the integrand is referenced via a `cellId` or/and an `ipId`. Maybe he can post some code but the idea is:

~~~cpp
struct DamageLaw
{
EngineeringStress Stress(EngineeringStrain strain, int ipId)
{
  double kappa = mHistoryData[ipId];
  return C * strain * (1 - Omega(kappa));
}
// ...
std::vector<double> mHistoryData;
};

struct MomentumBalance
{
Vector Gradient(CellData cellData, CellIpData)
{
   int ipId = cellData.cellId * numIps + cellIpData.ipId;
   auto strain = cellIpData.B() * cellData.Dofs(displacements);
   return cellIpData.B().transpose() * mLaw.Stress(strain, ipId);
}
};
~~~
This somehow couples the cell with the integrand. Imagine two materials. Material 1 is used for 100 cells and material 2 for 1000. You now need two define two separate cell groups (100 and 1000 cells). If you mix those, the second cell group (1000 cells) tries to access cell data of material 1 (only 100 cell data). IMO this boils down to: Instead of having the dynamic_cast as in our current concept, we now manually keep track of which cells play with which integrands. To provide a nice, uniform interface, in @Psirus original idea (I think), this was hidden in some operations magic. ~~If you follow the discussion in #43, the operations caused some confusion and criticism.~~ __Edit__: Nothing in #43 is related to this discussion. This was actually orally in our trip to GACM. 

We recently explored the option to _not_ have a uniform interface to the time integration schemes (#117, #62). This moves the internals of the former time integrations schemes to the `main` files, where the user knows all types of the objects and has total control. This __removes the need of `Operations`__ and makes handling the history data trivial.

~~~cpp
// your main file.
DamageLaw law(...);
MomentumBalance integrand(law, ...)
// "usual" code
auto gradient = assembler.Vector(cellGroup, integrand, &MomentumBalance::Gradient, ...);

// read some data
NuTo::SerializeStreamIn in("History.restart");
in >> law.mHistoryData;

// Jump some cycles;
//   at some point, make a copy
auto oldHistoryData = law.mHistoryData;
//   update history or something
//   jump!
for (int i = 0; i < law.mHistoryData.size(); ++i)
  law.mHistoryData[i] = SomeFunction(law.mHistoryData[i], oldHistoryData[i], numCycles);
~~~

**Comment by Psirus** [comment]
Solved in PDE.
