### ISSUE TITLE
Simplify BlockVector/matrix

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#56]
The DofStorage-containers like `BlockVector` or `BlockSparseMatrix` currently have the member `DofStatus` to optimize their behavoir. Mainly two features:
- `HasInteractingConstraints`
    - If there are no interacting constraints (constraints with multiple dofs in a single constraint equation), the terms `.KJ` and `.KK` can be ignored in the calculations. Thus, they are not assembled and multiplication and addition of sparse matrices only affect the `.JJ` and the `.JK` component.
- `IsActive`
    - In a multiphysics context, the multiple dof system can be solved in a _staggered_ way, one dof after the other, by setting dof types _active_. Arithmetic operations in the DofStorage containes will only affect the _active_ dof types. 

Based on the constant flow of incoming questions to both these topics, both features may cause more confusion than benefit. My suggestion: Completely remove everything involving `hasInteractingConstraints` from NuTo and remove the `activeDof` in the dof storage operators.

**Comment by joergfunger** [comment]
The IsActive Flag is in my opinion important. Even though it might cause
some confusion at the beginning, I don't know how to implement this
otherwise. Maybe we just need to improve the documentation:) .

For the HasInteractingConstraints Flag, I do not know, what the
computational advantage is. I assume that the savings are relatively low,
even though knowing this sometimes really simplifies the understanding of
the code (since this C matrix multiplication is usually not included in any
textbook).

Jörg F.

2017-06-18 21:48 GMT+02:00 TTitscher <notifications@github.com>:

**Comment by TTitscher** [comment]
Regarding IsActive. Do you think we need this as an actual feature or are you concerned about the performance? If it is _just_ the performance, the lazy evaluation mentioned in #57 may help. 

It is hard to get this whole IsActive to be consistent. E.g. the [copy constructor copies all the data](https://github.com/nutofem/nuto/blob/master/src/mechanics/dofSubMatrixStorage/BlockFullVector.cpp#L34), the [copy assignment copies _active_ dof data](https://github.com/nutofem/nuto/blob/master/src/mechanics/dofSubMatrixStorage/BlockFullVector.cpp#L69). This violates common guidelines and causes subtle bugs. How to solve that?

**Comment by Psirus** [comment]
As I see it, the block matrix should not have to know which part should be fettled with. So instead of
~~~cpp
dofStatus.SetActive(TEMPERATURE);
vector += blockVectorWithAdditionalTemperatureValues;
~~~
it should rather read
~~~cpp
vector.Get(Temperature) += additionalTemperatureValues;
~~~
But maybe I'm missing something here.

**Comment by TTitscher** [comment]
IMO I solved this issue. There are several problems when actually using the `active/inactive` dof type feature. One occurred in NewmarkDirect-Staggered.

The variable
~~~
LastConvergedDof = [ A   B ]^T
~~~
is independent of active or inactive dofs and contains the last converged dof vector. Now imagine a staggered step, where only `A` is active.

~~~
Dof = Solver.Solve(Matrix_A, Residual_A) = [ A_new   0]^T
~~~

If `Dof` is a converged state, we have to update the `LastConvergedDof`

~~~
// previously, where only the active dof types were assigned:
LastConvergedDof = Dof = [A_new   B(untouched)]^T

// now, when operator= does the same as copy-ctor:
LastConvergedDof = Dof = [A_new  0]^T 
~~~
The latter one is the behavior we agreed on and I solved the bug. So the general advice is: Do not modify variables that were defined _outside_ of the staggered loop. The proposal of @Psirus will definitely make things clearer. 
However, solved for now.
