### ISSUE TITLE
Serialization of stl containers with std::unique_ptr

### ISSUE THREAD

**Issue by potto1** [nutofem/nuto#8]
Since a  std::unique_ptr is a non-copyable object a move ctor has to be used in the serialization routines of the stl container. So far (tested with boost version 1.61) this is not possible, although a standalone std::unique_ptr is serializable.
See e.g. BlockSparseMatrix.h - L. 153

**Comment by TTitscher** [comment]
This problem can be solved by writing your own serialize template methods, e.g. see
https://github.com/CanalTP/utils/blob/master/serialization_unique_ptr_container.h

I added this to our own BoostExtensions and the serialization of e.g. BlockSparseMatrix.h works properly - including the Lobatto test case.
Unfortunately, there are many compile errors, if I activate all the options (VISUALIZE, METAMODEL, OPTIMIZE, etc..) Otherwise, I would have pushed it already. I try to fix this asap. So I guess, this can be closed.
